### ISSUE TITLE
Pokemon Generated Are Illegal According to PKHex

### ISSUE THREAD

**Issue by ColdStoneSys** [Goppier/GEN3PokemonDistributions#1]
I tested a few of the JP distributions and they showed up illegal in pkhex (STAMP Pichu, FESTA Metang, Sapporo Pikachu, and STAMP Absol).

Most of them have invalid met levels, and some PID-Encounter mismatches

**Comment by SmooshyBoops** [comment]
Pkhex doesn't have all the algorithms for a lot of gen 3 event pokemon. 
So while they appear illegal they are actually fine.
