### ISSUE TITLE
File paths collide in case-insensitive filesystems

### ISSUE THREAD

**Issue by wfowler1** [Goppier/GEN3PokemonDistributions#2]
For some reason there are ROMs that have the same name with different cases that break the repo on case-insensitive file systems (FAT based or NTFS).

English/PCNY/PCNYc/BUUJ - Spring Campaign C (ENG).Gba
English/PCNY/PCNYc/BUUJ - Spring Campaign C (ENG).gba

English/PCNY/PCNYd/BUUJ - Spring Campaign D (ENG).Gba
English/PCNY/PCNYd/BUUJ - Spring Campaign D (ENG).gba

**Comment by Goppier** [comment]
I have deleted the incorrect ROM and renamed the correct one to lower case ".gba".
